# Generated by Django 2.1.7 on 2019-06-25 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcerptModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=164, verbose_name='Source')),
                ('excerpt', models.CharField(max_length=128, verbose_name='Excerpt')),
                ('translation', models.CharField(max_length=128, verbose_name='Excerpt_translation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_excerpt', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
