# Generated by Django 2.1.7 on 2019-04-22 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name="Book's title")),
                ('image', models.ImageField(blank=True, upload_to="Book's image")),
            ],
        ),
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name="Author's name")),
                ('last_name', models.CharField(max_length=64, verbose_name="Author's last name")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_authors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=128, verbose_name='word')),
                ('translation', models.CharField(max_length=128, verbose_name='translation')),
                ('context', models.TextField(blank=True, verbose_name='context')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_words', to='userapp.Dictionary')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='userapp.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_words', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_books', to='userapp.Dictionary'),
        ),
        migrations.AddField(
            model_name='book',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_books', to=settings.AUTH_USER_MODEL),
        ),
    ]
